author:
  name   : "Md. Latifur Rahman Rafi"
  avatar : "/images/Prof_pic.jpeg"
  bio    : "AI Researcher | Teaching Assistant | Organizer"
  location : "Bangladesh"
  employer : "Daffodil AI Club"
  email  : "latifur23105101451@diu.edu.bd"
  github : "latifurraffi"
  linkedin : "your-linkedin"
