author:
  name   : "Md. Latifur Rahman Rafi"
  avatar : "/images/Profile_pic.jpeg"
  bio    : "AI Researcher | Teaching Assistant | Organizer"
  location : "Bangladesh"
  employer : "Daffodil AI Club"
  email  : "your@email.com"
  github : "latifurraffi"
